name: "Mkarchiso"
description: "Build an arch linux iso"
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: pacman -Sy --noconfirm archiso
      shell: bash
    - run: mkarchiso -v .
      shell: bash